export const coursesCategories = new Map([
  ["marketing", { label: "Marketing", color: "rgba(3, 206, 164, 1)" }],
  ["management", { label: "Management", color: "rgba(90, 135, 252, 1)" }],
  ["hr", { label: "HR & Recruting", color: "rgba(248, 152, 40, 1)" }],
  ["design", { label: "Design", color: "rgba(245, 47, 110, 1)" }],
  ["development", { label: "Development", color: "rgba(119, 114, 241, 1)" }],
]);

export const coursesData = [
  {
    id: 1,
    category: "marketing",
    title: "The Ultimate Google Ads Training Course",
    price: "$100",
    author: "Jerome Bell",
    imageUrl: "./people/image-01.webp",
  },
  {
    id: 2,
    category: "management",
    title: "Product Management Fundamentals",
    price: "$480",
    author: "Marvin McKinney",
    imageUrl: "./people/image-02.webp",
  },
  {
    id: 3,
    category: "hr",
    title: "HR Management and Analytics",
    price: "$200",
    author: "Leslie Alexander Li",
    imageUrl: "./people/image-03.webp",
  },
  {
    id: 4,
    category: "marketing",
    title: "Brand Management & PR Communications",
    price: "$530",
    author: "Kristin Watson",
    imageUrl: "./people/image-04.webp",
  },
  {
    id: 5,
    category: "design",
    title: "Graphic Design Basic",
    price: "$500",
    author: "Guy Hawkins",
    imageUrl: "./people/image-05.webp",
  },
  {
    id: 6,
    category: "management",
    title: "Business Development Management",
    price: "$400",
    author: "Dianne Russell",
    imageUrl: "./people/image-06.webp",
  },
  {
    id: 7,
    category: "development",
    title: "Highload Software Architecture",
    price: "$600",
    author: "Brooklyn Simmons",
    imageUrl: "./people/image-07.webp",
  },
  {
    id: 8,
    category: "hr",
    title: "Human Resources – Selection and Recruitment",
    price: "$150",
    author: "Kathryn Murphy",
    imageUrl: "./people/image-08.webp",
  },
  {
    id: 9,
    category: "design",
    title: "User Experience. Human-centered Design",
    price: "$240",
    author: "Cody Fisher",
    imageUrl: "./people/image-09.webp",
  },
];
